Repository ureca-yoajung/yoajung-service, pull requests merged in 2025-06, with the labels that each got.

#23 [feat] 리뷰 등록수정삭제, 좋아요 기능 구현
  build.gradle
  src/main/java/com/ureca/yoajungserver/common/BaseCode.java
  src/main/java/com/ureca/yoajungserver/review/advice/ReviewControllerAdvice.java
  src/main/java/com/ureca/yoajungserver/review/controller/ReviewController.java
  src/main/java/com/ureca/yoajungserver/review/dto/ReviewCreateRequest.java
  src/main/java/com/ureca/yoajungserver/review/dto/ReviewCreateResponse.java
  src/main/java/com/ureca/yoajungserver/review/dto/ReviewDeleteResponse.java
  src/main/java/com/ureca/yoajungserver/review/dto/ReviewLikeResponse.java
  src/main/java/com/ureca/yoajungserver/review/dto/ReviewListResponse.java
  src/main/java/com/ureca/yoajungserver/review/dto/ReviewUpdateRequest.java
  src/main/java/com/ureca/yoajungserver/review/dto/ReviewUpdateResponse.java
  src/main/java/com/ureca/yoajungserver/review/entity/Review.java
  src/main/java/com/ureca/yoajungserver/review/entity/ReviewLike.java
  src/main/java/com/ureca/yoajungserver/review/exception/DuplicatedReviewLikeException.java
  src/main/java/com/ureca/yoajungserver/review/exception/NotReviewAuthorException.java
  src/main/java/com/ureca/yoajungserver/review/exception/PlanNotFoundException.java
  src/main/java/com/ureca/yoajungserver/review/exception/ReviewAlreadyExistException.java
  src/main/java/com/ureca/yoajungserver/review/exception/ReviewNotAllowedException.java
  src/main/java/com/ureca/yoajungserver/review/exception/ReviewNotFoundException.java
  src/main/java/com/ureca/yoajungserver/review/exception/UserNotFoundException.java
  src/main/java/com/ureca/yoajungserver/review/repository/PlanRepository.java
  src/main/java/com/ureca/yoajungserver/review/repository/ReviewLikeRepository.java
  src/main/java/com/ureca/yoajungserver/review/repository/ReviewRepository.java
  src/main/java/com/ureca/yoajungserver/review/repository/UserRepository.java
  src/main/java/com/ureca/yoajungserver/review/service/ReviewService.java
  src/main/java/com/ureca/yoajungserver/review/service/ReviewServiceImpl.java
Labels: enhancement

#25 [feat] 회원가입 및 이메일 검증
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/ureca/yoajungserver/common/BaseCode.java
  src/main/java/com/ureca/yoajungserver/common/GlobalExceptionHandler.java
  src/main/java/com/ureca/yoajungserver/common/exception/BusinessException.java
  src/main/java/com/ureca/yoajungserver/config/RedisConfig.java
  src/main/java/com/ureca/yoajungserver/config/SecurityConfig.java
  src/main/java/com/ureca/yoajungserver/user/controller/AuthController.java
  src/main/java/com/ureca/yoajungserver/user/controller/UserController.java
  src/main/java/com/ureca/yoajungserver/user/dto/reqeust/SendCodeRequest.java
  src/main/java/com/ureca/yoajungserver/user/dto/reqeust/SignupRequest.java
  src/main/java/com/ureca/yoajungserver/user/dto/reqeust/VerifyCodeRequest.java
  src/main/java/com/ureca/yoajungserver/user/repository/UserRepository.java
  src/main/java/com/ureca/yoajungserver/user/service/AuthService.java
  src/main/java/com/ureca/yoajungserver/user/service/AuthServiceImpl.java
  src/main/java/com/ureca/yoajungserver/user/service/EmailService.java
  src/main/java/com/ureca/yoajungserver/user/service/EmailServiceImpl.java
  src/main/java/com/ureca/yoajungserver/user/service/UserService.java
  src/main/java/com/ureca/yoajungserver/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/ureca/yoajungserver/user/service/AuthServiceImplTest.java
  src/test/java/com/ureca/yoajungserver/user/service/EmailServiceImplTest.java
  src/test/java/com/ureca/yoajungserver/user/service/UserServiceImplTest.java
Labels: enhancement

#30 [fix] BaseCode 문법 오류 수정
  src/main/java/com/ureca/yoajungserver/common/BaseCode.java
Labels: bug

#34 [feat] 리뷰 조회 기능 구현
  src/main/java/com/ureca/yoajungserver/review/advice/ReviewControllerAdvice.java
  src/main/java/com/ureca/yoajungserver/review/controller/ReviewController.java
  src/main/java/com/ureca/yoajungserver/review/dto/request/ReviewCreateRequest.java
  src/main/java/com/ureca/yoajungserver/review/dto/request/ReviewUpdateRequest.java
  src/main/java/com/ureca/yoajungserver/review/dto/response/ReviewCreateResponse.java
  src/main/java/com/ureca/yoajungserver/review/dto/response/ReviewDeleteResponse.java
  src/main/java/com/ureca/yoajungserver/review/dto/response/ReviewLikeResponse.java
  src/main/java/com/ureca/yoajungserver/review/dto/response/ReviewListResponse.java
  src/main/java/com/ureca/yoajungserver/review/dto/response/ReviewPageResponse.java
  src/main/java/com/ureca/yoajungserver/review/dto/response/ReviewUpdateResponse.java
  src/main/java/com/ureca/yoajungserver/review/repository/ReviewRepository.java
  src/main/java/com/ureca/yoajungserver/review/repository/custom/ReviewRepositoryCustom.java
  src/main/java/com/ureca/yoajungserver/review/repository/custom/ReviewRepositoryImpl.java
  src/main/java/com/ureca/yoajungserver/review/service/ReviewService.java
  src/main/java/com/ureca/yoajungserver/review/service/ReviewServiceImpl.java
Labels: enhancement

#37 [feat] 리뷰 페이지 구현, 응답 데이터 및 쿼리 추가
  src/main/java/com/ureca/yoajungserver/review/controller/ReviewController.java
  src/main/java/com/ureca/yoajungserver/review/dto/response/ReviewListResponse.java
  src/main/java/com/ureca/yoajungserver/review/dto/response/ReviewPageResponse.java
  src/main/java/com/ureca/yoajungserver/review/repository/custom/ReviewRepositoryCustom.java
  src/main/java/com/ureca/yoajungserver/review/repository/custom/ReviewRepositoryImpl.java
  src/main/java/com/ureca/yoajungserver/review/service/ReviewService.java
  src/main/java/com/ureca/yoajungserver/review/service/ReviewServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/reviews/review.css
  src/main/resources/static/reviews/review.html
  src/main/resources/static/reviews/review.js
Labels: enhancement

#39 [feat] ChatMemory 엔티티 추가 및 테이블 이름 전략 수정
  src/main/java/com/ureca/yoajungserver/chatbot/entity/ChatMemory.java
  src/main/resources/application.yml
Labels: bug, enhancement

#42 [feat] 욕설 필터링 분리
  src/main/java/com/ureca/yoajungserver/chatbot/interceptor/GptBadWordInterceptor.java
  src/main/java/com/ureca/yoajungserver/chatbot/interceptor/LocalBadWordInterceptor.java
  src/main/java/com/ureca/yoajungserver/common/component/GptBadWordComponent.java
  src/main/java/com/ureca/yoajungserver/common/component/LocalBadWordComponent.java
  src/main/java/com/ureca/yoajungserver/common/config/WebConfig.java
  src/main/resources/application.yml
Labels: enhancement

#44 [feat] 리뷰 욕설 필터링 적용
  src/main/java/com/ureca/yoajungserver/chatbot/interceptor/GptBadWordInterceptor.java
  src/main/java/com/ureca/yoajungserver/chatbot/interceptor/LocalBadWordInterceptor.java
  src/main/java/com/ureca/yoajungserver/common/BaseCode.java
  src/main/java/com/ureca/yoajungserver/common/component/GptBadWordComponent.java
  src/main/java/com/ureca/yoajungserver/common/component/LocalBadWordComponent.java
  src/main/java/com/ureca/yoajungserver/review/exception/DuplicatedReviewLikeException.java
  src/main/java/com/ureca/yoajungserver/review/exception/NotReviewAuthorException.java
  src/main/java/com/ureca/yoajungserver/review/exception/PlanNotFoundException.java
  src/main/java/com/ureca/yoajungserver/review/exception/ReviewAlreadyExistException.java
  src/main/java/com/ureca/yoajungserver/review/exception/ReviewNotAllowedException.java
  src/main/java/com/ureca/yoajungserver/review/exception/ReviewNotFoundException.java
  src/main/java/com/ureca/yoajungserver/review/exception/UserNotFoundException.java
  src/main/java/com/ureca/yoajungserver/review/repository/custom/ReviewRepositoryImpl.java
  src/main/java/com/ureca/yoajungserver/review/service/ReviewServiceImpl.java
Labels: enhancement

#51 [feat] 유저 성향 최초 조회, 수정 삭제
  src/main/java/com/ureca/yoajungserver/common/BaseCode.java
  src/main/java/com/ureca/yoajungserver/common/GlobalExceptionHandler.java
  src/main/java/com/ureca/yoajungserver/user/controller/TendencyController.java
  src/main/java/com/ureca/yoajungserver/user/controller/UserController.java
  src/main/java/com/ureca/yoajungserver/user/dto/reqeust/TendencyRequest.java
  src/main/java/com/ureca/yoajungserver/user/dto/response/TendencyResponse.java
  src/main/java/com/ureca/yoajungserver/user/entity/Tendency.java
  src/main/java/com/ureca/yoajungserver/user/exception/TendencyAlreadyExistsException.java
  src/main/java/com/ureca/yoajungserver/user/exception/TendencyNotFoundException.java
  src/main/java/com/ureca/yoajungserver/user/repository/TendencyRepository.java
  src/main/java/com/ureca/yoajungserver/user/service/TendencyService.java
  src/main/java/com/ureca/yoajungserver/user/service/TendencyServiceImpl.java
Labels: enhancement

#54 [feat] 리뷰에 시큐리티 적용 및 인증여부에 따라 리뷰조회 쿼리 분기
  src/main/java/com/ureca/yoajungserver/review/dto/response/ReviewPageResponse.java
  src/main/java/com/ureca/yoajungserver/review/repository/custom/ReviewRepositoryImpl.java
  src/main/java/com/ureca/yoajungserver/review/service/ReviewServiceImpl.java
  src/main/resources/static/reviews/review.js
Labels: enhancement

#63 [feat] ChatClient 응답을 PlanKeywordResponse 엔티티로 매핑
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotServiceImpl.java
Labels: refactor

#65 [refactor] 엔티티 구조 관리자 서버와 일치화
  src/main/java/com/ureca/yoajungserver/plan/entity/Plan.java
  src/main/java/com/ureca/yoajungserver/plan/entity/PlanBenefit.java
  src/main/java/com/ureca/yoajungserver/plan/entity/PlanProduct.java
  src/main/java/com/ureca/yoajungserver/user/entity/AgeGroup.java
Labels: refactor

#67 feat: frontend 기본 셋팅
  src/main/resources/static/assets/css/index.css
  src/main/resources/static/assets/css/login.css
  src/main/resources/static/assets/css/myPage.css
  src/main/resources/static/assets/css/plan-detail.css
  src/main/resources/static/assets/css/plan-list.css
  src/main/resources/static/assets/css/signup.css
  src/main/resources/static/assets/image/yoajung.png
  src/main/resources/static/assets/navbar.html
  src/main/resources/static/chatbot-test.html
  src/main/resources/static/chatbot.html
  src/main/resources/static/index.html
  src/main/resources/static/login.html
  src/main/resources/static/myPage.html
  src/main/resources/static/plan-detail.html
  src/main/resources/static/plan-list.html
  src/main/resources/static/signup.html
Labels: enhancement

#72 [feat] 챗봇 키워드로 요금제 조회
  src/main/java/com/ureca/yoajungserver/chatbot/controller/ChatbotController.java
  src/main/java/com/ureca/yoajungserver/chatbot/dto/BenefitEntry.java
  src/main/java/com/ureca/yoajungserver/chatbot/dto/PersonalPlanListResponse.java
  src/main/java/com/ureca/yoajungserver/chatbot/dto/PersonalPlanRecommendResponse.java
  src/main/java/com/ureca/yoajungserver/chatbot/repository/ChatbotRepository.java
  src/main/java/com/ureca/yoajungserver/chatbot/repository/ChatbotRepositoryImpl.java
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotService.java
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/ureca/yoajungserver/plan/entity/Benefit.java
  src/main/java/com/ureca/yoajungserver/plan/entity/Plan.java
  src/main/java/com/ureca/yoajungserver/plan/entity/PlanBenefit.java
  src/main/java/com/ureca/yoajungserver/plan/entity/PlanProduct.java
  src/main/java/com/ureca/yoajungserver/plan/entity/Product.java
  src/main/resources/application.yml
  src/main/resources/prompt/prompt.txt
Labels: enhancement

#71 [feat] 요금제 정렬 및 연령대 필터 추가, benefit 조회
  src/main/java/com/ureca/yoajungserver/plan/dto/request/PlanFilterRequest.java
  src/main/java/com/ureca/yoajungserver/plan/dto/response/PlanFilterResponse.java
  src/main/java/com/ureca/yoajungserver/plan/entity/PlanStatistic.java
  src/main/java/com/ureca/yoajungserver/plan/repository/PlanFilterRepository.java
  src/main/java/com/ureca/yoajungserver/plan/repository/PlanStatisticRepository.java
  src/main/resources/static/plan-test.html
Labels: enhancement

#80 [fix] 챗봇 요금제 조회 쿼리 수정
  src/main/java/com/ureca/yoajungserver/chatbot/controller/TestController.java
  src/main/java/com/ureca/yoajungserver/chatbot/dto/PlanKeywordResponse.java
  src/main/java/com/ureca/yoajungserver/chatbot/repository/ChatbotRepositoryImpl.java
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotService.java
  src/main/resources/application.yml
  src/main/resources/prompt/prompt.txt
  src/main/resources/static/chatbot.html
Labels: enhancement

#86 [Feat] 리뷰 프론트 연결
  src/main/java/com/ureca/yoajungserver/review/service/ReviewServiceImpl.java
  src/main/resources/static/assets/css/plan-detail-review.css
  src/main/resources/static/assets/css/plan-detail.css
  src/main/resources/static/plan-detail.html
Labels: enhancement

#98 [feat] 챗봇 쿼리 수정
  src/main/java/com/ureca/yoajungserver/chatbot/dto/PlanKeywordResponse.java
  src/main/java/com/ureca/yoajungserver/chatbot/repository/ChatbotRepositoryImpl.java
  src/main/java/com/ureca/yoajungserver/config/SecurityConfig.java
  src/main/resources/prompt/prompt.txt
  src/main/resources/static/assets/css/mypage.css
Labels: enhancement

#109 [Feat] 챗봇 성능 개선
  src/main/java/com/ureca/yoajungserver/YoajungServerApplication.java
  src/main/java/com/ureca/yoajungserver/chatbot/repository/ChatbotRepositoryImpl.java
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/ureca/yoajungserver/chatbot/service/LLMAsyncService.java
  src/main/java/com/ureca/yoajungserver/config/AsyncConfig.java
  src/main/resources/prompt/prompt1.txt
  src/main/resources/prompt/prompt2.txt
  src/main/resources/prompt/prompt3.txt
  src/main/resources/static/chatbot.html
Labels: bug, enhancement

#101 [fix] 상세 페이지 ui 수정
  src/main/java/com/ureca/yoajungserver/plan/exception/InvalidPlanCategoryException.java
  src/main/java/com/ureca/yoajungserver/plan/exception/InvalidPlanSortTypeException.java
  src/main/java/com/ureca/yoajungserver/plan/exception/PlanNotFoundException.java
  src/main/java/com/ureca/yoajungserver/plan/service/PlanServiceImpl.java
  src/main/resources/static/plan-detail.html
Labels: enhancement

#111 [feat] favicon 등록
  src/main/resources/static/favicon.ico
Labels: bug

#119 [fix] 충돌 해결
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/ureca/yoajungserver/review/service/ReviewServiceImpl.java
Labels: bug

#125 [fix] jpa Lazy 로딩 transaction 시 fetch join
  src/main/java/com/ureca/yoajungserver/api/oauth/OAuthServiceImpl.java
  src/main/java/com/ureca/yoajungserver/user/dto/response/UserResponse.java
  src/main/java/com/ureca/yoajungserver/user/repository/UserRepository.java
  src/main/resources/static/callback.html
  src/main/resources/static/mypage.html
Labels: fix

#128 [feat] 챗봇 욕설 필터링 적용
  src/main/java/com/ureca/yoajungserver/config/WebConfig.java
  src/main/resources/static/chatbot.html
Labels: enhancement

#132 [feat] 키워드 추출 실패 시 사용자에게 재질문 로직 구현
  src/main/java/com/ureca/yoajungserver/chatbot/dto/PlanKeywordResponse.java
  src/main/java/com/ureca/yoajungserver/chatbot/exception/KeywordExtractionFailedException.java
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/ureca/yoajungserver/common/BaseCode.java
  src/main/resources/static/chatbot.html
Labels: enhancement

#131 [fix] chatmemory 복구
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotServiceImpl.java
  src/main/resources/application.yml
Labels: bug

#140 [fix] 멀티턴 수정
  src/main/java/com/ureca/yoajungserver/chatbot/repository/ChatbotRepositoryImpl.java
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotServiceImpl.java
Labels: bug

#149 [Fix] 리뷰 프론트 수정
  src/main/resources/static/assets/css/plan-detail-review.css
  src/main/resources/static/assets/js/plan-detail-common.js
  src/main/resources/static/assets/js/plan-review.js
Labels: bug

#151 [Feat] 프론트 수정
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/ureca/yoajungserver/config/AIConfig.java
  src/main/java/com/ureca/yoajungserver/plan/entity/PlanTarget.java
  src/main/resources/static/assets/css/chatbot.css
  src/main/resources/static/assets/js/alert.js
  src/main/resources/static/chatbot.html
  src/main/resources/static/index.html
Labels: enhancement

#153 [Feature] 상세 페이지 챗봇 연결
  src/main/java/com/ureca/yoajungserver/plan/service/PlanRecommendService.java
  src/main/resources/static/assets/css/plan-detail.css
  src/main/resources/static/assets/image/recommendationAi.png
  src/main/resources/static/assets/js/login-navbar.js
  src/main/resources/static/assets/js/plan-detail-common.js
  src/main/resources/static/plan-detail.html
  src/main/resources/static/plan-list.html
Labels: enhancement

#154 [feat] 채팅 대화 기록 저장
  src/main/java/com/ureca/yoajungserver/chatbot/entity/ChatHistory.java
  src/main/java/com/ureca/yoajungserver/chatbot/entity/ChatType.java
  src/main/java/com/ureca/yoajungserver/chatbot/repository/ChatHistoryRepository.java
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotServiceImpl.java
Labels: bug, enhancement

#158 [Feat] 챗봇 성능 개선 및 프론트 디자인 수정
  src/main/java/com/ureca/yoajungserver/chatbot/service/ChatbotServiceImpl.java
  src/main/java/com/ureca/yoajungserver/chatbot/service/LLMAsyncService.java
  src/main/java/com/ureca/yoajungserver/config/AIConfig.java
  src/main/resources/application.yml
  src/main/resources/static/assets/css/chatbot.css
  src/main/resources/static/assets/navbar.html
  src/main/resources/static/chatbot.html
  src/main/resources/static/index.html
Labels: enhancement

#156 [feat] 요금제 리뷰 AI 요약 조회 기능
  src/main/java/com/ureca/yoajungserver/common/BaseCode.java
  src/main/java/com/ureca/yoajungserver/summary/controller/PlanSummaryController.java
  src/main/java/com/ureca/yoajungserver/summary/dto/PlanSummaryDto.java
  src/main/java/com/ureca/yoajungserver/summary/entity/PlanSummary.java
  src/main/java/com/ureca/yoajungserver/summary/repository/PlanSummaryRepository.java
  src/main/java/com/ureca/yoajungserver/summary/service/PlanSummaryService.java
  src/main/resources/application.yml
  src/main/resources/static/assets/css/plan-detail.css
  src/main/resources/static/assets/js/plan-detail.js
  src/main/resources/static/plan-detail.html
Labels: enhancement

#163 feat: 유저/인증/비밀번호/성향/OAuth 테스트 코드 및 픽스처 추가
  build.gradle
  docker-compose.test.yml
  src/main/java/com/ureca/yoajungserver/plan/entity/Plan.java
  src/main/java/com/ureca/yoajungserver/user/service/EmailServiceImpl.java
  src/test/java/com/ureca/yoajungserver/authentication/fixture/AuthFixture.java
  src/test/java/com/ureca/yoajungserver/authentication/service/AuthServiceImplTest.java
  src/test/java/com/ureca/yoajungserver/email/fixture/EmailFixture.java
  src/test/java/com/ureca/yoajungserver/email/service/EmailServiceImpTest.java
  src/test/java/com/ureca/yoajungserver/oauth/fixture/KakaoSignupRequestFixture.java
  src/test/java/com/ureca/yoajungserver/oauth/service/OAuthServiceImplTest.java
  src/test/java/com/ureca/yoajungserver/password/fixture/PasswordResetFixture.java
  src/test/java/com/ureca/yoajungserver/password/service/PasswordResetServiceImplTest.java
  src/test/java/com/ureca/yoajungserver/tendency/fixture/TendencyFixture.java
  src/test/java/com/ureca/yoajungserver/tendency/fixture/TendencyRequestFixture.java
  src/test/java/com/ureca/yoajungserver/tendency/service/TendencyServiceImplTest.java
  src/test/java/com/ureca/yoajungserver/user/fixture/PlanFixture.java
  src/test/java/com/ureca/yoajungserver/user/fixture/SignupRequestFixture.java
  src/test/java/com/ureca/yoajungserver/user/fixture/UserFixture.java
  src/test/java/com/ureca/yoajungserver/user/fixture/UserUpdateRequestFixture.java
  src/test/java/com/ureca/yoajungserver/user/service/AuthServiceImplTest.java
  src/test/java/com/ureca/yoajungserver/user/service/EmailServiceImplTest.java
  src/test/java/com/ureca/yoajungserver/user/service/UserServiceImplTest.java
  src/test/resources/application-test.yml
Labels: test

#169 [refactor] 말풍선 위치변경
  src/main/resources/static/assets/css/plan-detail.css
Labels: fix

#171 feat: swagger API 문서화 인터페이스 추가
  build.gradle
  src/main/java/com/ureca/yoajungserver/api/oauth/OAuthController.java
  src/main/java/com/ureca/yoajungserver/chatbot/controller/ChatbotController.java
  src/main/java/com/ureca/yoajungserver/config/SwaggerConfig.java
  src/main/java/com/ureca/yoajungserver/plan/controller/PlanController.java
  src/main/java/com/ureca/yoajungserver/plan/controller/PlanFilterController.java
  src/main/java/com/ureca/yoajungserver/plan/controller/PlanRecommendController.java
  src/main/java/com/ureca/yoajungserver/product/controller/ProductController.java
  src/main/java/com/ureca/yoajungserver/review/controller/ReviewController.java
  src/main/java/com/ureca/yoajungserver/summary/controller/PlanSummaryController.java
  src/main/java/com/ureca/yoajungserver/swagger/api/AuthControllerSwagger.java
  src/main/java/com/ureca/yoajungserver/swagger/api/ChatbotControllerSwagger.java
  src/main/java/com/ureca/yoajungserver/swagger/api/OAuthControllerSwagger.java
  src/main/java/com/ureca/yoajungserver/swagger/api/PlanControllerSwagger.java
  src/main/java/com/ureca/yoajungserver/swagger/api/PlanFilterControllerSwagger.java
  src/main/java/com/ureca/yoajungserver/swagger/api/PlanRecommendControllerSwagger.java
  src/main/java/com/ureca/yoajungserver/swagger/api/PlanSummaryControllerSwagger.java
  src/main/java/com/ureca/yoajungserver/swagger/api/ProductControllerSwagger.java
  src/main/java/com/ureca/yoajungserver/swagger/api/ReviewControllerSwagger.java
  src/main/java/com/ureca/yoajungserver/swagger/api/TendencyControllerSwagger.java
  src/main/java/com/ureca/yoajungserver/swagger/api/UserControllerSwagger.java
  src/main/java/com/ureca/yoajungserver/swagger/error/ErrorCode400.java
  src/main/java/com/ureca/yoajungserver/swagger/error/ErrorCode401.java
  src/main/java/com/ureca/yoajungserver/swagger/error/ErrorCode403.java
  src/main/java/com/ureca/yoajungserver/swagger/error/ErrorCode404.java
  src/main/java/com/ureca/yoajungserver/swagger/error/ErrorCode409.java
  src/main/java/com/ureca/yoajungserver/swagger/error/ErrorCode500.java
  src/main/java/com/ureca/yoajungserver/swagger/response/ApiCreatedResponse.java
  src/main/java/com/ureca/yoajungserver/swagger/response/ApiNoContentResponse.java
  src/main/java/com/ureca/yoajungserver/swagger/response/ApiSuccessResponse.java
  src/main/java/com/ureca/yoajungserver/user/controller/AuthController.java
  src/main/java/com/ureca/yoajungserver/user/controller/TendencyController.java
  src/main/java/com/ureca/yoajungserver/user/controller/UserController.java
  src/main/java/com/ureca/yoajungserver/user/dto/reqeust/TendencyRequest.java
  src/main/java/com/ureca/yoajungserver/user/service/PasswordResetServiceImpl.java
  src/main/resources/application.yml
Labels: documentation, enhancement
